### ISSUE TITLE
update .htaccess setup to improve page speed

### ISSUE THREAD

**Issue by k33** [multiple-states/bread-butter#23]
Use Google Page speed for suggestions

See examples such as:

http://www.feedthebot.com/pagespeed/leverage-browser-caching.html
http://stackoverflow.com/questions/20131039/setting-an-expiry-date-or-a-maximum-age-in-the-http-headers
http://betterexplained.com/articles/how-to-optimize-your-site-with-gzip-compression/

**Comment by willmcl** [comment]
https://github.com/multiple-states/bread-butter/issues/34
https://github.com/multiple-states/bread-butter/issues/35
