### ISSUE TITLE
Redirect www to non-www 

### ISSUE THREAD

**Issue by k33** [multiple-states/bread-butter#27]
To do this we need to add a .htaccess file with the following code:

RewriteEngine On
RewriteCond %{HTTP_HOST} !^www\.
RewriteRule ^(.*)$ http://www.%{HTTP_HOST}/$1 [R=301,L]

**Comment by willmcl** [comment]
We skipped 0.9.2 so will do this in the development for 0.10.0

**Comment by willmcl** [comment]
This code redirects the wrong way, ie. non-www to www. I have left this for the next version as I am not familiar enough with redirects.

**Comment by willmcl** [comment]
k33 can you expand on the reasoning for this being included? To me this seems project specific?

**Comment by willmcl** [comment]
Wontfix. Project specific.
