### ISSUE TITLE
Grunt cssmin task is incorrectly compiling relative url() paths in the css

### ISSUE THREAD

**Issue by willmcl** [multiple-states/bread-butter#56]
This can be fixed with:

```
options: {
    rebase: false
  },
  files: {
    ...
  }
```

https://github.com/gruntjs/grunt-contrib-cssmin/issues/173

**Comment by k33** [comment]
The option rebase is set to false by default: https://github.com/gruntjs/grunt-contrib-cssmin/commit/77100010d7695d8e36aafef116c25f3922c0762b
